### ISSUE TITLE
Nginx option

### ISSUE THREAD

**Issue by Park0** [inoxio/ansible-role-ispconfig3#5]
I would like to use ISP-config with nginx. I used the follow code:

```
---
- hosts: all
  become: true

  roles:
    - role: inoxio.ispconfig3
      tags: ispconfig
      mail_admin_email: isp-config@domain.lan
      mail_base_domain: domain.lan
      ispconfig_hostname: server.lan
      roundcube_hostname: mail.lan
      phpmyadmin_hostname: phpmyadmin.lan
      ispconfig_configure_firewall: n
      ispconfig_do_backup: n
      ispconfig_configure_apache: n
      ispconfig_configure_nginx: y

```
But i still get apache2.
